apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: model-serving
subjects:
- kind: ServiceAccount
  name: "116885968878138943915"
  namespace: model-serving
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
